### ISSUE TITLE
How do I install Mainnet

### ISSUE THREAD

**Issue by ghost** [fioprotocol/fio.start#18]
This tutorial seems to be installing Testnet. How should I start a primary network node

**Comment by ghost** [comment]
Very anxious, please see the reply, we are very grateful

**Comment by cc32d9** [comment]
see the mainnet details here: https://github.com/fioprotocol/fio.mainnet

**Comment by adsorptionenthalpy** [comment]
Closing this issue. @satonz Please join our discord or telegram channels for further support if you cannot connect with mainnet details provided.
